///////////////////////////////////////////////////////////
//  Rectangle.cs
//  Implementation of the Class Rectangle
//  Generated by Enterprise Architect
//  Created on:      05-???-2018 19:15:49
//  Original author: Nikita Butsko
///////////////////////////////////////////////////////////




public class Rectangle : Parallelogram {

	public Rectangle(){

	}

	~Rectangle(){

	}

	public override void Dispose(){

	}

	public abstract override void draw();

	public override vector<Point> location(){

		return null;
	}

	/// 
	/// <param name="destination"></param>
	public abstract override void move(Point destination);

}//end Rectangle