///////////////////////////////////////////////////////////
//  Circle.cs
//  Implementation of the Class Circle
//  Generated by Enterprise Architect
//  Created on:      05-???-2018 19:15:42
//  Original author: Nikita
///////////////////////////////////////////////////////////




public class Circle : Ellipse {

	public Circle(){

	}

	~Circle(){

	}

	public override void Dispose(){

	}

	public abstract void draw();

	public abstract vector<Point> location();

	/// 
	/// <param name="destination"></param>
	public abstract void move(Point destination);

}//end Circle