///////////////////////////////////////////////////////////
//  DoubleDimensional.cs
//  Implementation of the Class DoubleDimensional
//  Generated by Enterprise Architect
//  Created on:      05-???-2018 19:15:44
//  Original author: HP
///////////////////////////////////////////////////////////




public abstract class DoubleDimensional : Shape {

	private Color fillColor;

	public DoubleDimensional(){

	}

	~DoubleDimensional(){

	}

	public override void Dispose(){

	}

	public Color getFillColor(){

		return null;
	}

	/// 
	/// <param name="newVal"></param>
	public void setFillColor(Color newVal){

	}

}//end DoubleDimensional