///////////////////////////////////////////////////////////
//  IsoscelesTriangle.cs
//  Implementation of the Class IsoscelesTriangle
//  Generated by Enterprise Architect
//  Created on:      05-???-2018 19:15:45
//  Original author: Nikita Butsko
///////////////////////////////////////////////////////////




public class IsoscelesTriangle : RightTriangle {

	private int point;

	public IsoscelesTriangle(){

	}

	~IsoscelesTriangle(){

	}

	public override void Dispose(){

	}

	public override void draw(){

	}

	public int GetPoint(){

		return 0;
	}

	public override vector<Point> location(){

		return null;
	}

	/// 
	/// <param name="destination"></param>
	public override void move(Point destination){

	}

	/// 
	/// <param name="newVal"></param>
	public void SetPoint(int newVal){

	}

}//end IsoscelesTriangle