///////////////////////////////////////////////////////////
//  LineSegment.cs
//  Implementation of the Class LineSegment
//  Generated by Enterprise Architect
//  Created on:      05-???-2018 19:15:46
//  Original author: Nikita Butsko
///////////////////////////////////////////////////////////




public class LineSegment : Ray {

	public LineSegment(){

	}

	~LineSegment(){

	}

	public override void Dispose(){

	}

	public abstract void draw();

	public abstract vector<Point> location();

	/// 
	/// <param name="destination"></param>
	public abstract void move(Point destination);

}//end LineSegment