///////////////////////////////////////////////////////////
//  OneDimensional.cs
//  Implementation of the Class OneDimensional
//  Generated by Enterprise Architect
//  Created on:      05-???-2018 19:15:47
//  Original author: HP
///////////////////////////////////////////////////////////




public abstract class OneDimensional : Shape {

	public OneDimensional(){

	}

	~OneDimensional(){

	}

	public override void Dispose(){

	}

}//end OneDimensional