///////////////////////////////////////////////////////////
//  Ray.cs
//  Implementation of the Class Ray
//  Generated by Enterprise Architect
//  Created on:      05-???-2018 19:15:49
//  Original author: Nikita Butsko
///////////////////////////////////////////////////////////




public class Ray : Line {

	public Ray(){

	}

	~Ray(){

	}

	public override void Dispose(){

	}

	public abstract void draw();

	public abstract vector<Point> location();

	/// 
	/// <param name="destination"></param>
	public abstract void move(Point destination);

}//end Ray